### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Jelldo** [kookmin-sw/2019-cap1-2019_5#165]
에러 핸들링, 버그 등등
자유롭게 추가하시고 확인된 부분은 체크해주세요

- Frontend
- [x] 위치 입력내용 삭제 기능
- [x] 초기화면으로 갈 수 있는 기능
- [x] 지정한 인원수만 입력할 수 있는 기능
- [x] 인원수에 1이상 정수만 입력하도록 하는 기능
- [x] 최대인원수 제출현황에 표시
- [x] 일정 인원수가 되어야 결과 제출 버튼 활성화되도록 하는 기능
- [x] 대중교통 / 자동차 선택하게 하고 backend에 해당 데이터 보내는 기능
- [x] 투표 내용 제출 기능
- [x] config 폴더 및 파일 만들기
- [x] 마커를 클릭하면 해당 결과가 보이는 기능
- [x] 검색기준지점 위치 변경하기 (왼쪽 레이어쪽으로)
- [x] 검색기준지점 위치 가시화하기 (왼쪽레이어나 맵 위 어딘가?)
- [x] 결과창 여백 줄이기 & 투표버튼 살려내기

- Backend
- [x] 경로 삭제 가능하게 하는 기능
- [x] Crawling을 통해 얻은 포스팅들 그룹화해서 지역 레이팅 정하기
- [x] Dummy rating data와 기존의 지역 레이팅을 합쳐서 최종 레이팅 구하기
- [x] Rating을 기준으로 정렬하는 기능

**Comment by Jelldo** [comment]
BRILLIANT! 😝
Cheers y'all!
